# Generated by Django 5.1.6 on 2025-03-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheese', '0003_user2'),
    ]

    operations = [
        migrations.CreateModel(
            name='user3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user3',
            },
        ),
    ]
