# Generated by Django 5.1.6 on 2025-03-01 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheese', '0004_user3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user3',
        ),
    ]
