# Generated by Django 5.1.6 on 2025-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheese', '0005_delete_user3'),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'index',
            },
        ),
    ]
