# Generated by Django 5.1.6 on 2025-03-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheese', '0007_rename_index_call_alter_call_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user2',
            new_name='ecom',
        ),
        migrations.DeleteModel(
            name='call',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AlterModelTable(
            name='ecom',
            table='ecom',
        ),
    ]
