# Generated by Django 5.1.6 on 2025-03-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheese', '0008_rename_user2_ecom_delete_call_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('head', models.IntegerField()),
                ('cal', models.DateField()),
            ],
            options={
                'db_table': 'call',
            },
        ),
    ]
