# Generated by Django 5.1.6 on 2025-03-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheese', '0009_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='head',
            field=models.CharField(max_length=50),
        ),
    ]
