# Generated by Django 5.1.6 on 2025-03-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheese', '0010_alter_call_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='head',
        ),
    ]
